version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cursifynova-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cursifypass
    networks:
      - cursifynova-network

  redis:
    image: redis:latest
    container_name: cursifynova-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cursifynova-network

networks:
  cursifynova-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: